### ISSUE TITLE
Error: A rooted tree is not ultrametric

### ISSUE THREAD

**Issue by mticlla** [YanHanChen/iNEXTPD2#2]
Hi YanHanCHen,

Thank you very much for developing iNextPD2. I've imported a nwk tree with ape::read.tree() and then used iNEXTPD() but I get the following error:

Error in get.rooted.tree.height(mytree) : 
  A rooted tree is not ultrametric

I'm not sure if I should try to force the tree to be ultrametric or if there is a way to run iNEXTPD() on a non-ultrametric tree?

Thanks for the help,

Monica

**Comment by YanHanChen** [comment]
Hi Monica,

Currently, the methodology is developed for an ultrametric tree so please transform the non-ultrametric tree into an ultrametric one. Please let me know if you have further questions. 

Yan Han
